name: proyecto_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - r-base
  - r-tidyverse
  - bioconductor-deseq2
  - bioconductor-edger
  - bioconductor-limma
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - biopython
